[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
default-run = "app"
edition = "2018"
build = "src/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.0.0-beta.3" }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.0.0-beta.5", features = ["api-all"] }
postgrest = "1.0"
reqwest = { version = "0.11", features = ["json"] }
titlecase = "1.1"
dirs = "3.0"
thiserror = "1.0"
anyhow = "1.0"
base64 = "0.13"
futures = "0.3"
chad-torrent = { git = "https://gitlab.com/Gnurur/chad-torrent" }
enum_dispatch = "0.3"
enum-kinds = "=0.5.0" # Temporary

[lib]
name = "chad_launcher"
path = "src/lib.rs"

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
