image: "rust:bullseye"

before_script:
    - apt update -yqq && apt install -yqq --no-install-recommends nodejs npm libwebkit2gtk-4.0-dev build-essential curl wget libssl-dev libgtk-3-dev libappindicator3-dev patchelf librsvg2-dev

build:
  script:
    - npm install
    - npm run build
    - npm run tauri build
    
publish:
  script:
    - cp src-tauri/target/release/chad-launcher chad-launcher
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  artifacts:
    paths:
      - chad-launcher
