image: "rust:bullseye"

cache:
  - key: pnpm
    paths:
      - .pnpm-store
  - key: cargo
    paths:
      - src-tauri/target

before_script:
    - apt update -yqq && apt install -yqq --no-install-recommends nodejs libwebkit2gtk-4.0-dev build-essential curl wget libssl-dev libgtk-3-dev patchelf librsvg2-dev
    - curl -f https://get.pnpm.io/v6.14.js | node - add --global pnpm@6    
    - pnpm config set store-dir .pnpm-store

build:
  script:
    - pnpm install
    - pnpm run build
    - pnpm run tauri build
    - cp src-tauri/target/release/chad-launcher chad-launcher
  #rules:
    #- if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  artifacts:
    paths:
      - chad-launcher

