image: "rust:bullseye"

cache:
  - key: pnpm
    paths:
      - .pnpm-store
  - key: cargo
    paths:
      - src-tauri/target

before_script:
    - apt update -yqq && apt install -yqq --no-install-recommends nodejs libwebkit2gtk-4.0-dev build-essential curl wget libssl-dev libgtk-3-dev patchelf librsvg2-dev
    - curl -f https://get.pnpm.io/v6.14.js | node - add --global pnpm@6    
    - pnpm config set store-dir .pnpm-store

stages:
  - tauri:build
  - package

tauri:build:
  stage: tauri:build
  script:
    - pnpm install
    - pnpm run build
    - pnpm run tauri build
    - cp src-tauri/target/release/chad-launcher chad-launcher
    # Copy most recent deb file
    - cp `ls -t src-tauri/target/release/bundle/deb/*.deb | head -1` chad-launcher.deb 
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  artifacts:
    paths:
      - chad-launcher
      - chad-launcher.deb


package:
  stage: package
  image: whynothugo/makepkg
  script:
    cp chad-launcher pkgbuild/ci
    cp chad_launcher.desktop pkgbuid/ci
    cp icon.svg pkgbuild/ci
    cd pkgbuild/ci
    makepkg -s
    cp chad_launcher-bin-*.pkg.tar.xz ../../chad-launcher.pkg.tar.xz
  artifacts:
    paths:
      - chad-launcher
      - chad-launcher.deb
      - chad-launcher.pkg.tar.xz

    
